import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Header from '../components/header'
import Comment from '../components/comment'

const Home: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
      </Head>

      <Header/>

      <main className={styles.main}>
        <div className={styles.homeContent}>
          <div className={styles.homeContentText}>
            <div className="text-wrapper">
              <h2>Explore A <br/>Great <br/>Restaurant</h2>
              <p>Everyone can be Michelin judge</p>
            </div>
            <button>Explore Restaurant by Map</button>
          </div>
          <div className={styles.homeContentList}>
            <Comment/>
          </div>
        </div>
        <div className={styles.bgMap}>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d544.3700686603115!2d120.71904646395606!3d24.249023027270827!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x34691a05c7b90025%3A0xfb359f7286c533fa!2z5Zq06ZuqIOmbquiKseWGsOWwiOizo-W6lw!5e0!3m2!1szh-TW!2stw!4v1666603034025!5m2!1szh-TW!2stw" width="100%" height="100%" style={{border:0}} allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
